### ISSUE TITLE
OPPOR15手机选择图片 崩溃率达到98%

### ISSUE THREAD

**Issue by lr784521** [chavesgu/images_picker#87]
Process: com.one.flutterdemo, PID: 29952
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
        at e.b.a.c.e(Unknown Source:14)
        at e.b.a.c.a(Unknown Source:0)
        at e.b.a.c$a$a.run(Unknown Source:95)

**Comment by MR-MaoJiu** [comment]
一样问题。。。有解决吗

**Comment by MR-MaoJiu** [comment]
Bitmap bitmap = ThumbnailUtils.createVideoThumbnail(path, MediaStore.Video.Thumbnails.FULL_SCREEN_KIND);
    if (bitmap != null) {
      ByteArrayOutputStream bytes = new ByteArrayOutputStream();
      bitmap.compress(Bitmap.CompressFormat.JPEG, 100, bytes);
      try {
        File outputDir = context.getCacheDir();
        File outputFile = File.createTempFile("image_picker_thumb_"+ UUID.randomUUID().toString(), ".jpg", outputDir);
        FileOutputStream fo = new FileOutputStream(outputFile);
        fo.write(bytes.toByteArray());
        fo.close();
        return outputFile.getAbsolutePath();
      } catch (IOException e) {
        e.printStackTrace();
      }
    }手动改一下就行
